site_name: Soil Data Assimilation Guidance
site_description: "Cookbook for a masterclass on Soil Data Assimilation"
site_author: Wageningen Environmental Research
copyright: "&copy; 2022-2023 Wageningen Environmental Research"
site_url: https://ejpsoil.github.io/soildata-assimilation-guidance
repo_url: https://github.com/ejpsoil/soildata-assimilation-guidance
docs_dir: docs
nav:
    - Home: index.md
    - 'Identification': 
        - Intro: identification.md
        - Uri strategy: cookbook/uri.md
    - 'Harmonization': 
        - Intro: etl.md
        - 'Relational database': cookbook/glosis-db.md
        - 'Hale Studio': cookbook/hale-studio.md
        - TARQL: cookbook/tarql.md
        - YARRRML: cookbook/rml.md
    - 'Code lists': 
        - 'Intro': codelists.md
        - 'Filebased': cookbook/codelist-iso19135.md
        - 'Re3gistry': cookbook/re3gistry.md
        - 'Skosmos': cookbook/virtuoso.md
        - 'Extend code lists': cookbook/code-listsExtension.md
    - 'Discovery': 
        - Metadata: metadata.md
        - pygeometa: cookbook/pygeometa.md
        - DCAT: cookbook/dcat.md
        - GeoNetwork: cookbook/geonetwork.md
    - View: 
        - View: view.md
        - MapServer: cookbook/mapserver.md
        - GeoServer: cookbook/bridge-geoserver-geonetwork.md
        - 'QGIS server': cookbook/qgis.md
    - Download: 
        - Intro: download.md
        - Webdav: cookbook/webdav.md
        - Zenodo: cookbook/zenodo.md
        - GeoServer: cookbook/geoserver.md
        - deegree: cookbook/deegree.md
        - 'CSW Rasdaman': cookbook/rasdaman.md
        - 'SensorThings API' : cookbook/frost-server.md
        - pygeoapi: cookbook/pygeoapi.md
        - LDProxy: cookbook/ldproxy.md
        - GraphQL: cookbook/postgraphile.md
    - QOS: QOS.md
    - Utils:
        - docker: utils/docker.md
        - gdal: utils/gdal.md
        - git: utils/git.md
        - jupyter: utils/jupyter.md
        - tunnel: utils/localtunnel.md
        - r: utils/r.md
        - visualstudiocode: utils/visualstudiocode.md
        - python: utils/python.md

theme:
    name: material
    logo: https://ejpsoil.eu/fileadmin/projects/ejpsoil/EJP_Soil_logo_cmyk-h100.png
    favicon: https://cdn.au.dk/favicon.ico

extra:
  homepage: https://ejpsoil.eu/

plugins:
    - search

markdown_extensions:
    - admonition